# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

Credits: https://github.com/mrdbourke

In [48]:
# Import NumPy as its abbreviation 'np'

import numpy as np

In [49]:
# Create a 1-dimensional NumPy array using np.array()

one_dim = np.array([1])

# Create a 2-dimensional NumPy array using np.array()

two_dim = np.array([1,2])

# Create a 3-dimensional Numpy array using np.array()

three_dim = np.array([
    [
        [1,2,3],
        [4,5,6],
    ],
    [
        [1,2,3],
        [4,5,6]
    ]

])

one_dim, two_dim, three_dim


(array([1]),
 array([1, 2]),
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [50]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_dim.shape, one_dim.ndim, one_dim.dtype, one_dim.size, type(one_dim)

((1,), 1, dtype('int64'), 1, numpy.ndarray)

In [51]:
# Attributes of 2-dimensional array
two_dim.shape, two_dim.ndim, two_dim.dtype, two_dim.size, type(two_dim)

((2,), 1, dtype('int64'), 2, numpy.ndarray)

In [52]:
# Attributes of 3-dimensional array
three_dim.shape, three_dim.ndim, three_dim.dtype, three_dim.size, type(three_dim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [53]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

df = pd.DataFrame(two_dim)
df

,0
0,1
1,2


In [54]:
# Create an array of shape (10, 2) with only ones

ones = np.zeros((10,2))
ones[0:10] = 1
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(((7,2,3)))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [56]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.arange(0,100,3)
array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [57]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_array = np.random.randint(1,10, size=(7,2))
rand_array


array([[9, 1],
       [3, 7],
       [4, 9],
       [3, 5],
       [3, 7],
       [5, 9],
       [7, 2]])

In [58]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

rand_array_f = np.random.random(size = (3,5))
rand_array_f

array([[0.94888554, 0.96563203, 0.80839735, 0.30461377, 0.09767211],
       [0.68423303, 0.44015249, 0.12203823, 0.49517691, 0.03438852],
       [0.9093204 , 0.25877998, 0.66252228, 0.31171108, 0.52006802]])

In [59]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [65]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(0,10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(array)

array([0, 2, 3, 4, 5, 6, 8, 9])

In [69]:
# Find the 0'th index of the latest array you created
array[0]

array([5, 2, 0, 2, 4, 2, 0])

In [71]:
# Get the first 2 rows of latest array you created
array[:2]

array([[5, 2, 0, 2, 4, 2, 0],
       [4, 9, 6, 6, 8, 9, 9]])

In [72]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:2]

array([[5, 2],
       [4, 9]])

In [94]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array2 = np.random.randint(0,10, size=(3,5))
array3 = np.random.randint(1,2, size=(3,5))

In [95]:
# Add the two arrays together
array2 + array3

array([[7, 4, 7, 8, 1],
       [6, 8, 5, 4, 2],
       [6, 6, 1, 9, 6]])

In [96]:
# Create another array of ones of shape (5, 3)
array4 = np.random.randint(1,2, size=(5,3))
array4.shape

(5, 3)

In [97]:
# Try add the array of ones and the other most recent array together
array2 + array4

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [98]:
array4 = array4.T
array5 = array4 + array2

In [99]:
# Create another array of ones of shape (3, 5)
array6 = np.random.randint(1,2, size=(3,5))

In [101]:
# Subtract the new array of ones from the other most recent array
array7 = array5 - array6

In [103]:
# Multiply the ones array with the latest array
array8 = array7 * array6
array8

array([[6, 3, 6, 7, 0],
       [5, 7, 4, 3, 1],
       [5, 5, 0, 8, 5]])

In [107]:
# Take the latest array to the power of 2 using '**'
array9 = (array8**2)

In [105]:
# Do the same thing with np.square()
np.square(array8)

array([[36,  9, 36, 49,  0],
       [25, 49, 16,  9,  1],
       [25, 25,  0, 64, 25]])

In [108]:
# Find the mean of the latest array using np.mean()
np.mean(array9)

np.float64(24.6)

In [109]:
# Find the maximum of the latest array using np.max()
np.max(array9)

np.int64(64)

In [110]:
# Find the minimum of the latest array using np.min()
np.min(array9)

np.int64(0)

In [111]:
# Find the standard deviation of the latest array
np.std(array9)

np.float64(18.853116453255147)

In [112]:
# Find the variance of the latest array
np.var(array9)

np.float64(355.43999999999994)

In [115]:
# Reshape the latest array to (3, 5, 1)
array10 = array9.reshape(3,5,1)
array10

array([[[36],
        [ 9],
        [36],
        [49],
        [ 0]],

       [[25],
        [49],
        [16],
        [ 9],
        [ 1]],

       [[25],
        [25],
        [ 0],
        [64],
        [25]]])

In [116]:
# Transpose the latest array
array10 = array10.T
array10

array([[[36, 25, 25],
        [ 9, 49, 25],
        [36, 16,  0],
        [49,  9, 64],
        [ 0,  1, 25]]])

What does the transpose do?
$$A = \begin{bmatrix}
i_1,j_1 & i_2,j_1 \\
i_1,j_2 & i_2,j_2
\end{bmatrix}\\[10pt]
B = \begin{bmatrix}
i_1,j_1 & i_1,j_2 \\
i_2,j_1 & i_1,j_2 
\end{bmatrix}$$

It flips the matrix along the diagonal, $ 3 \times 5 \text{ becomes } 5 \times 3$

In [118]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array33 = np.random.randint(0,10, size=(3,3))
array32 = np.random.randint(0,10, size=(3,2))

In [119]:
# Perform a dot product on the two newest arrays you created
np.dot(array33,array32)

array([[24, 40],
       [18, 81],
       [42, 43]])

In [120]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_1 = np.random.randint(0,10, size=(4,3))
array_2 = np.random.randint(0,10, size=(4,3))

In [121]:
# Perform a dot product on the two newest arrays you created
np.dot(array_1,array_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [122]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_1.T, array_2)

array([[122, 129,  93],
       [ 36,  36,  34],
       [ 78,  86,  57]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

the dot product of arrays (or matrices) the vertical values against the horizontal values, so the vertical of one must match the horizontal of the second

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [140]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_3 = np.random.randint(0,10, size=(4,4))
array_4 = np.random.randint(0,10, size=(4,4))

In [141]:
# Compare the two arrays with '>'
array_3 > array_4

array([[False, False, False,  True],
       [ True,  True, False,  True],
       [False,  True, False,  True],
       [False, False, False,  True]])

What happens when you compare the arrays with `>`?

Boolean comparison

In [142]:
# Compare the two arrays with '>='
array_3 >= array_4

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True, False,  True,  True]])

In [143]:
# Find which elements of the first array are greater than 7
print(np.argwhere(array_3 > 7))
    

[]


In [144]:
# Which parts of each array are equal? (try using '==')
print(np.argwhere(array_3==array_4))

[[0 2]
 [1 2]
 [2 2]
 [3 0]
 [3 2]]


In [145]:
# Sort one of the arrays you just created in ascending order
array_3 = np.sort(array_3)
array_3

array([[0, 0, 2, 5],
       [5, 5, 5, 6],
       [1, 2, 5, 7],
       [0, 0, 4, 4]])

In [ ]:
# Sort the indexes of one of the arrays you just created
np.sort(array_3, axis=1)

array([[0, 0, 2, 5],
       [5, 5, 5, 6],
       [1, 2, 5, 7],
       [0, 0, 4, 4]])

In [160]:
# Find the index with the maximum value in one of the arrays you've created
print('(',np.argmax(array_3)//4,',', np.argmax(array_3)%4,')')

( 2 , 3 )


In [161]:
# Find the index with the minimum value in one of the arrays you've created
print('(',np.argmin(array_3)//4,',', np.argmin(array_3)%4,')')

( 0 , 0 )


In [162]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_3, axis=1)

array([3, 3, 3, 2])

In [163]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_3, axis=1)

array([0, 0, 0, 0])

In [179]:
# Create an array of normally distributed random numbers
norm_array = np.random.normal(0,100, size=(4,4))


In [45]:
# Create an array with 10 evenly spaced numbers between 1 and 100
spaced = np.arange(1,100,10)
spaced

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.